use_frameworks!
 target 'PhotoSharer' do
 pod 'NVActivityIndicatorView', '4.6.1'
 pod 'SnapKit', '4.2.0'
 pod 'IQKeyboardManagerSwift', '6.0.4'
 pod 'FacebookCore', '0.5.0'
 pod 'FacebookLogin', '0.5.0'
 pod 'FacebookShare', '0.5.0'
 pod 'TwitterKit'
end
